Explicitely ignore return code when calling controllerutil.SetOwnerReference() ang getSubscription()
Linter fails with:
controllers/pattern_controller.go:139:34: Error return value of `controllerutil.SetOwnerReference` is not checked (errcheck)
        controllerutil.SetOwnerReference(qualifiedInstance, targetSub, r.Scheme)

We are explicitely ignoring it, because returning when err != nil would
result in:
Reconcile step "Set targetSub owner reference" failed: cross-namespace owner references are disallowed, owner's namespace default, obj's namespace openshift-operators